// Bundles server/*.ts into single-file ESM functions in api/, which Vercel
// deploys as-is. Bundling keeps the shared engine in src/core as the one
// source of truth without relying on Vercel resolving TS imports across folders.
// Run `npm run build:api` before committing server changes.
import { build } from 'esbuild';

const entries = ['tick', 'test-push'];

await build({
  entryPoints: Object.fromEntries(entries.map((e) => [e, `server/${e}.ts`])),
  outdir: 'api',
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  minify: false,
  legalComments: 'none',
  banner: {
    js: [
      '// GENERATED by scripts/build-api.mjs from server/. Do not edit.',
      "import { createRequire as __cr } from 'module'; const require = __cr(import.meta.url);",
      // web-push still calls url.parse(); its deprecation notice would log as an error on every run.
      'process.noDeprecation = true;',
    ].join('\n'),
  },
  logLevel: 'info',
});
